### ISSUE TITLE
Stairs block vision?

### ISSUE THREAD

**Issue by a3qz** [a3qz/hag#126]

**Comment by a3qz** [comment]
![image](https://user-images.githubusercontent.com/10551746/73420203-8e890380-42d6-11ea-84e9-74773b44f3f5.png)

**Comment by JohnathonNow** [comment]
Yes I knew about this. Should it be fixed?

**Comment by a3qz** [comment]
Maybe up stairs should block down shouldn't? I'd prefer either that or none at all on the stairs

**Comment by a3qz** [comment]
![image](https://user-images.githubusercontent.com/10551746/77121274-0d0d4200-69f8-11ea-94bc-ba743a8528ba.png)
still happens post that pr

**Comment by JohnathonNow** [comment]
Should be fixed... Again...
