### ISSUE TITLE
Demo system

### ISSUE THREAD

**Issue by JohnathonNow** [a3qz/hag#132]
A nice touch would be a demo system where players could choose to save a run of the game. This would be easy to produce as a binary file containing only the initial seed value as well as every keystroke made during the game. This file would be compact (limited to roughly 100KB because of the maximum floor tick count) and actually gives an easy way to save game progress.

**Comment by JohnathonNow** [comment]
I think it would want to look something like
[VERSION][SEED][KEYSTROKE]*
Where VERSION is a single byte version number - perhaps later we want to add the time between keystrokes, etc, this simplifies this future change. SEED is four bytes, making up the seed value. Finally, any number of simple byte KEYSTROKEs indicate the keys that are pressed.

**Comment by a3qz** [comment]
Why not use compression? pressing the same key in a row is a pretty common action, unless we want to care about time.  
re: time
if we keep the time, these demo files can be used for speedrunning.  if we dont they cannot.

**Comment by JohnathonNow** [comment]
If we keep time then how would compression work?

**Comment by a3qz** [comment]
i was defaulting to not keeping time

**Comment by JohnathonNow** [comment]
We can do compression later, for now just the basic form, versioned at 1.

**Comment by JohnathonNow** [comment]
Closed by #150
