### ISSUE TITLE
Change enemy movement

### ISSUE THREAD

**Issue by JohnathonNow** [a3qz/hag#138]
https://github.com/a3qz/hag/blob/7eaeaf5c0a01260ce606f40aaac880bbee5ddbcf/src/logic/enemy_rulebook.c#L263-L274

There are two big problems with this piece of code.

1. Why are there empty else blocks?
2. The movement order is flipped from the convention established by Old School RuneScape. This should be fixed.

**Comment by Vishu7758** [comment]
Hey I'm really a beginner. I want to give this a shot..

**Comment by Vishu7758** [comment]
Sorry but I'm not getting your code base..I'm going to stop..anyone wants to contribute please go ahead.
