### ISSUE TITLE
action_add does not copy strings

### ISSUE THREAD

**Issue by JohnathonNow** [a3qz/hag#33]
Because it doesn't if you malloc a string and call action_add on it, we will have a memory leak. If we do a global string then changing it after calling action_add will change it in both places.

**Comment by JohnathonNow** [comment]
Also it seems if your message is shorter than a previous one it doesn't clear past it.

**Comment by dontworrybhappy** [comment]
I think I fixed this. Take a look at the pull request for the "tweak" branch.
