### ISSUE TITLE
Key is off

### ISSUE THREAD

**Issue by JohnathonNow** [a3qz/hag#47]
![2018-03-04-180639_3200x1080_scrot](https://user-images.githubusercontent.com/5497725/36951925-39e0d354-1fd7-11e8-9786-98c34f584c35.png)
![2018-03-04-180636_3200x1080_scrot](https://user-images.githubusercontent.com/5497725/36951926-39f0f950-1fd7-11e8-8aed-b886c30dad91.png)

**Comment by a3qz** [comment]
what was the context of this happening?

**Comment by JohnathonNow** [comment]
I'm not quite sure. Occasionally it seems to just ignore things. Perhaps it is tied to #23

**Comment by a3qz** [comment]
I think it might be tied to my if statements in [this](https://github.com/a3qz/hag/blob/master/key.c#L46)

**Comment by a3qz** [comment]
can you check out the logic? i based them off of code I didnt write so maybe I misunderstood them

**Comment by dontworrybhappy** [comment]
fixed it
