### ISSUE TITLE
Inspect Potions

### ISSUE THREAD

**Issue by JohnathonNow** [a3qz/hag#69]
Right now you have no idea whether a potion is good or bad. This makes the game stressful.

I was thinking we could have a system that tells you, with some probability, whether something good or bad will happen if you drink the potion.

**Comment by JohnathonNow** [comment]
@a3qz suggested we have the result of inspecting a potion be what stat it changes.

**Comment by dcbaok** [comment]
Added a PR for this.  
I (captial i) to inspect a potion you're standing on.

There's a probability that you'll be able to identify the stat the potion changes, which increases with player level and the number of potions you've used.

Once a potion has been inspected it can't be re-inspected so unknown potions remain unknown.

May want to change the chance of identification - game balance is not my call. Could cap the potion memory as well to prevent spamming potions for later easy identification.

**Comment by JohnathonNow** [comment]
Fixed by #88.
