### ISSUE TITLE
Warp to the end of floor 1 bug

### ISSUE THREAD

**Issue by JohnathonNow** [a3qz/hag#73]
The "climb up the first floor" bug was actually just a trick to warp to the end of floor 1 - see [this line](https://github.com/a3qz/hag/blob/master/src/floor.c#L152).

Personally, at this point changing it would probably upset the speedrunners.

**Comment by a3qz** [comment]
I agree that this is the result - I don't think it is by design, however.  

True, if we fixed it now no one would run the newer versions of the game

**Comment by JohnathonNow** [comment]
Should it be a feature flag?
```
#if NO_WARP
```
?

**Comment by a3qz** [comment]
No, we should just make the call on if we keep it or not

**Comment by JohnathonNow** [comment]
Personally I don't think there should be a ladder on the first floor. In fact, I'd almost prefer something like the first floor is "outdoors", with green ground tiles.
