### ISSUE TITLE
Optionally show player controls

### ISSUE THREAD

**Issue by ginglis13** [a3qz/hag#76]
Just started checking out `hag`, looks like a fun game. I've found myself referring to the README quite often to figure out the commands used for the game. I thought it might be a good idea to have an optional cmdline arg to show controls for newer players. I was originally thinking that a good place for this might be under the stats in the right side panel, but I think that might get too cluttered. Another option might be to not have the controls passed as an argument but to instead have maybe ESC bound to toggling a popup with the controls listed.

Lmk what you think, and if it's something you might want implemented, I'll take a stab at it.

**Comment by JohnathonNow** [comment]
I'm all for it, personally.
I'm not sure how @a3qz would feel about it, though. Perhaps he'd be keen if the flag were somehow calling the player a "babby".

**Comment by a3qz** [comment]
I like the idea of a button or something that shows the controls, that seems more elegant

**Comment by a3qz** [comment]
Instead of a pop-up it could even just log them out nicely in the text window

**Comment by ginglis13** [comment]
Sounds good. I'll make a pr soon.
