### ISSUE TITLE
All output of help command <?> will not be readable if window is too small

### ISSUE THREAD

**Issue by a3qz** [a3qz/hag#89]

**Comment by a3qz** [comment]
@ginglis13 
we don't actually have a way to fix this right now, but if you want to dig deep and work on our log system you could

**Comment by JohnathonNow** [comment]
I have also experienced this. Do we want some way to scroll back through the log? Or perhaps make a minimum log window size?

**Comment by a3qz** [comment]
I would like scrolling through the log

**Comment by ginglis13** [comment]
I can take a look at this over the weekend.

**Comment by a3qz** [comment]
You don't necessarily need to own this if you dont want @ginglis13 , it is more a general new feature of the log box than it is specifically about the ? command.  That just happens to be the first command that prints more than two lines at once.
