### ISSUE TITLE
Create controls header

### ISSUE THREAD

**Issue by JohnathonNow** [a3qz/hag#97]
Right now all of the keys are defined inside `main.c`. It is probably better to have a separate header that defines each of the controls. 

While doing so, the controls could be cleaned up a little. Namely, the debugging cheat key `'c'` should probably be removed, as well as the `'t'` command that is commented out. Additionally, I'm not sure the fallthrough attribute is necessary with the current warning flags, nor what the best practice is surrounding this.

**Comment by Luis-gd** [comment]
can i take it?

**Comment by Luis-gd** [comment]
Do you want to make a controls.h to define all the controls and controls.c to create a function for each control?

**Comment by JohnathonNow** [comment]
Just a header defining some constants is probably fine for now.
The movement keys are tricky because we have two sets of them, perhaps something like
`const int MOVE_W = 'h';`  
and
`const int MOVE_W_BABBY = 0xWhateverTheHexCodeForLeftArrowKeyIs;`

**Comment by Luis-gd** [comment]
Ok, understanded

**Comment by JohnathonNow** [comment]
This seems like it was solved.
