### ISSUE TITLE
Improve organization

### ISSUE THREAD

**Issue by JohnathonNow** [a3qz/hag#98]
We are getting to the point that there are many source files all in the same directory. This looks daunting and a bit cluttered. Is there any sensible way to organize the source files into folders?

**Comment by JohnathonNow** [comment]
I'm thinking
`main` and `args` can be in a `core` directory,  
`map` and `floor` can be in a `world` directory,  
`flavortext`, `gui`, `key`, and `colors` can be under `ui`,  
`list` can be under `util`  
then maybe `player`, `enemy`, `items`, `enemy_rulebook` can all be under `game_logic`

**Comment by a3qz** [comment]
I agree with this, we should organize these files better and this makes sense

**Comment by JohnathonNow** [comment]
Solved by #115.
